### ISSUE TITLE
怎么没有"subscribe": 

### ISSUE THREAD

**Issue by 503945930** [node-webot/wechat-oauth#13]
在获取用户信息的时候，怎么没有"subscribe": 字段

**Comment by JacksonTian** [comment]
以微信文档为准：http://mp.weixin.qq.com/wiki/4/9ac2e7b1f1d22e9e57260f6553822520.html

**Comment by 503945930** [comment]
这应该是以前的文档吧 我用php就可以获取这个，subscribe这个字段是判读是否关注了微信号的。[http://www.cnblogs.com/txw1958/p/weixin76-user-info.html](http://www.cnblogs.com/txw1958/p/weixin76-user-info.html)

**Comment by 503945930** [comment]
已经解决，找错地方了。应该在这里面找 [https://github.com/node-webot/wechat-api](https://github.com/node-webot/wechat-api).谢谢。

**Comment by 503945930** [comment]
已经解决。[https://github.com/node-webot/wechat-api](https://github.com/node-webot/wechat-api)
