### ISSUE TITLE
按照Wechat， Wechat-Api项目的AccessToken的定义，最好让AccessToken保持一致

### ISSUE THREAD

**Issue by w304807481** [node-webot/wechat-oauth#15]
多一个data节点 容易让大家误解，略显多余。
建议如下
var AccessToken = function (data) {
  if (!(this instanceof AccessToken)) {
    return new AccessToken(data);
  }
  this.expireTime = data.expire_time;
  this.accessToken = data.access_token;
  this.expireIn = data.expires_in;
  this.refreshToken = data.refresh_token;
  this.openid = data.openid;
  this.scope = data.scope;
};

...
AccessToken.prototype.isValid = function () {
  return !!this.accessToken && (new Date().getTime()) < this.expireTime;
};

**Comment by superlbr** [comment]
+1，根本没法跟wechat-api共存

**Comment by superlbr** [comment]
即使改造成一样的格式，但是出现了好多400001

**Comment by superlbr** [comment]
![image](https://cloud.githubusercontent.com/assets/8142164/19626803/52ff4f12-996b-11e6-937b-0cf3827b896f.png)
囧，两个access_token 还不一样

**Comment by JacksonTian** [comment]
不是同一个东西。OAuth只能调用少量接口。
