### ISSUE TITLE
getUser中最后一行的token是AccessToken!!! 

### ISSUE THREAD

**Issue by palmtale** [node-webot/wechat-oauth#16]
在getUser最后一段是说发现token过期了， 执行refreshToken。
但回调里用了token.access_token。应该是token.data.access_token.

因为refreshToken中会processToken ,  processToken中的 saveToken里在callback时给data 包裹为AccessToken.,  

请尽快修复，不然满满的都是41001

**Comment by w304807481** [comment]
我已经修了， 并提交了PR
