### ISSUE TITLE
getAuthorizeURLForWebsite 不能正常工作

### ISSUE THREAD

**Issue by jejer** [node-webot/wechat-oauth#17]
//res.redirect(wx.getAuthorizeURL(full_url, 'jejer', 'snsapi_userinfo'));
            res.redirect(wx.getAuthorizeURLForWebsite(full_url, 'jejer', 'snsapi_userinfo')

同样的参数 getAuthorizeURL 正常, getAuthorizeURLForWebsite 返回 "Scope 参数错误或没有 Scope 权限" 
生成的URL: https://open.weixin.qq.com/connect/qrconnect?appid=wxbca42d4004221261&redirect_uri=http%3A%2F%2Fujkk1e90d62d.jejer.koding.io%2Findex.html&response_type=code&scope=snsapi_login&state=#wechat_redirect

**Comment by czciou** [comment]
+1

**Comment by czciou** [comment]
解决了么？ @jejer

**Comment by jejer** [comment]
@czciou 后来没再看

**Comment by JacksonTian** [comment]
看下官方文档是否有改动？

**Comment by czciou** [comment]
解决了。清楚微信分公众平台和开放平台就能解决这个问题
