### ISSUE TITLE
授权回调页面，刷新当前页access_token问题

### ISSUE THREAD

**Issue by morongs** [node-webot/wechat-oauth#23]
@JacksonTian 在页面授权之后，回调到新的地址，通过code值获取access_token正常返回数据，但是在这个页面刷新，就出现了WeChatAPIError: invalid code的错误：
{ [WeChatAPIError: invalid code, hints: [ req_id: rA.hRA0175ns87 ]] name: 'WeChatAPIError', code: 40029 }
TypeError: Cannot read property 'access_token' of undefined
    at E:\www\node-pgy\routes\pages\account.js:67:32
    at E:\www\node-pgy\node_modules\wechat-oauth\lib\oauth.js:33:14
    at E:\www\node-pgy\node_modules\wechat-oauth\lib\util.js:18:14

**Comment by JacksonTian** [comment]
登录成功后，需要记录到session中。code不能反复用。

**Comment by morongs** [comment]
好的，thx
