### ISSUE TITLE
静默授权根据 openid 获取用户信息时报错 api unauthorized

### ISSUE THREAD

**Issue by keng42** [node-webot/wechat-oauth#27]
根据 openid 获取用户信息的接口 url 有2个：
https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN_1&openid=OPENID&lang=zh_CN  
https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN_2&openid=OPENID&lang=zh_CN  
其中 ACCESS_TOKEN_1 是根据 appid 和 appsecret 获取到的，ACCESS_TOKEN_2 是网页授权获取到的。  
官方文档现在的版本只给了第一种方式。  
用户关注公众号之后静默授权(snsapi_base)获取用户信息的情况只能用第一种方式，用第二种方式的话会报错 `api unauthorized`  
而目前 `wechat-oauth` 使用的是第二种方式。
  
  
另外，一个诡异的情况是：  
两个服务号，同样的代码（使用第二种方式），一个能获取到用户信息，另一个报错。找不到原因。

**Comment by JacksonTian** [comment]
你有一个服务号没有权限而已。

**Comment by keng42** [comment]
@JacksonTian  不知道你所指的权限是不是这个？
`网页授权获取用户基本信息`
<img width="769" alt="screen shot 2016-12-09 at 14 09 18" src="https://cloud.githubusercontent.com/assets/11435662/21039477/22f5198c-be19-11e6-9d7a-356e682a4db5.png">
`网页授权域名`也设置好没问题的。

**Comment by charlieqiang** [comment]
您好。为什么我获取的返回值是{"errcode":48001,"errmsg":"api unauthorized hints: [jHmbeZXMRa-Rkng4a!]"}?
