### ISSUE TITLE
能不能在这个库里面加入PC端授权登录一起，谢谢

### ISSUE THREAD

**Issue by weixumian** [node-webot/wechat-oauth#3]
PC端的授权登录也可以做到这个库里面就好了，谢谢
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&lang=zh_CN&token=054359a7aeac94af41041962741fea6ab49888a9

**Comment by ifeiteng** [comment]
PC端的授权登录？你是指网站应用开发里的微信登录和移动应用开发里的微信登录吗？

**Comment by ifeiteng** [comment]
看了下文档，授权后接口调用的API和公众号网页授权登录是没有区别的，你可以测试一下，有问题再反馈

**Comment by weixumian** [comment]
感谢，的确，授权之后的部分都是一样的，是可以一起使用的

**Comment by JacksonTian** [comment]
那就close了咯
