### ISSUE TITLE
Unable to resolve module `util`

### ISSUE THREAD

**Issue by Josin22** [node-webot/wechat-oauth#32]
error: bundling: UnableToResolveError: Unable to resolve module `util` from `../wechat-oauth/lib/oauth.js`: Module does not exist in the module map or in these directories:

**Comment by JacksonTian** [comment]
util 是 node 的内置模块。

**Comment by Josin22** [comment]
wechat-oauth不支持react-native项目吗?,

**Comment by JacksonTian** [comment]
wechat-oauth is a Node.js library, not a react-native lib.
