### ISSUE TITLE
getUser方法的API文档有个小错误

### ISSUE THREAD

**Issue by yeyuqiudeng** [node-webot/wechat-oauth#35]
文档地址： [http://doxmate.cool/node-webot/wechat-oauth/api.html#oauth__getUser](http://doxmate.cool/node-webot/wechat-oauth/api.html#oauth__getUser)

```
openId
// 或
{
 "openId": "the open Id", // 必须
 "lang": "the lang code" // zh_CN 简体，zh_TW 繁体，en 英语
}

```
`getUser` 的文档如上，`option` 的 `openId` 应该是 `openid`。

每次用这个方法的时候，都去源码瞄一眼，确定一下有没有记错。

**Comment by JacksonTian** [comment]
fixed.
