### ISSUE TITLE
getUser方法返回值是一个数组，好有问题

### ISSUE THREAD

**Issue by wadecha** [node-webot/wechat-oauth#39]
[ { openid: 'oZl-s1COCKUqk5wiil6Cvv5Hi_ek',
    nickname: 'xx',
    sex: 1,
    language: 'zh_CN',
    city: 'Shenzhen',
    province: 'Guangdong',
    country: 'China',
    headimgurl: 'http://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKiahZyV5lvsQRzzhR2K7mDSuHn1Sc14azr2nSKVSPz5Qj7lGiasvcQdt1yM8mnYIIgg/0',
    privilege: [] },
  { status: 200,
    statusCode: 200,
    headers: 
     { connection: 'keep-alive',
       'content-type': 'text/plain',
       date: 'Wed, 20 Sep 2017 04:20:28 GMT',
       'content-length': '307' },
    size: 307,
    aborted: false,
    rt: 211,
    keepAliveSocket: false,
    data: 
     { openid: 'oZl-s1COCKUqk5wiil6Cvv5Hi_ek',
       nickname: 'xx',
       sex: 1,
       language: 'zh_CN',
       city: 'Shenzhen',
       province: 'Guangdong',
       country: 'China',
       headimgurl: 'http://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKiahZyV5lvsQRzzhR2K7mDSuHn1Sc14azr2nSKVSPz5Qj7lGiasvcQdt1yM8mnYIIgg/0',
       privilege: [] } } ]

**Comment by JacksonTian** [comment]
请问你是怎么用的？

**Comment by wadecha** [comment]
co(function* () {
    const oauthUser = yield cb1 => oauthClient.getUserByCode(code, cb1);
    console.log(oauthUser);
  })
    .catch();

**Comment by wadecha** [comment]
有没有可能是调用库冲突？

**Comment by JacksonTian** [comment]
推荐你用 co-wechat-oauth

**Comment by wadecha** [comment]
我用的是 co 库，用的是 node 6.11.0 稳定版本，你那个库是要 await，我用的这个还不支持

**Comment by wadecha** [comment]
我看了，我也想用 co-wechat-oauth，试过会报错

**Comment by JacksonTian** [comment]
用 1.x  版本。

**Comment by wadecha** [comment]
那我试试吧，你们用的node 版本都是 7以上的么

**Comment by JacksonTian** [comment]
生产只用 LTS 版本。

**Comment by JacksonTian** [comment]
https://github.com/node-webot/co-wechat-oauth/tree/1.x
