### ISSUE TITLE
ios下网页授权后，点返回，提示40029-不合法的oauth_code

### ISSUE THREAD

**Issue by looping84** [node-webot/wechat-oauth#4]
我有个单独的url比如 aouth/aouth(假设叫A页面)
其他页面都会去这个A页面认证，当用户从 A页面跳到B页面。
然后在B页面点返回，A页面的时候，

ios下会立即提示 `40029-不合法的oauth_code`

android下没有返回按钮，点后退按钮没问题。

**Comment by JacksonTian** [comment]
什么情况下要点返回呢

**Comment by looping84** [comment]
@JacksonTian  从A => B=>C  用户在C页操作完成后，有的需要在返回到B页，这个时候，B页面中的，能拿到req.query.code 
*client.getAccessToken(req.query.code*   但是直接进error。
我的场景是：用户A页面提交数据，B页面是个列表页，C是详情页

**Comment by JacksonTian** [comment]
我猜问题是code只能用一次。你用code获得用户之后，加入进session中。如果session中显示有用户了 就不要再去走这个流程了。

**Comment by looping84** [comment]
@JacksonTian  有道理，我现在又给跳转到授权页，让他重新来一次。我一会试试你的方法
