### ISSUE TITLE
client里面不能用await?

### ISSUE THREAD

**Issue by maxcheers86** [node-webot/wechat-oauth#40]
错误提示：await is a reserved word 
放在client外面就不会出错！
有什么解决办法？

**Comment by JacksonTian** [comment]
show me your code.

**Comment by maxcheers86** [comment]
thinkjs 3.0 controller file
![qq 20171014154057](https://user-images.githubusercontent.com/22199234/31573849-43bada8c-b0f6-11e7-9ab5-23ae1c59cfc7.png)

**Comment by maxcheers86** [comment]
换个思路，用think.promisify对client包装一下
problem solved
