### ISSUE TITLE
wechat mini program support

### ISSUE THREAD

**Issue by aojiaotage** [node-webot/wechat-oauth#43]
Mini-programs got a similar but slightly different mechanism compared to wechat OAuth process. Auth URL, eg. 
I wonder if there is any possible plan for supporting that?
Could I just create a PR for that?

**Comment by JacksonTian** [comment]
PR welcome.

**Comment by JacksonTian** [comment]
PR welcome.

**Comment by JacksonTian** [comment]
PR welcome.

**Comment by JacksonTian** [comment]
PR welcome.

**Comment by JacksonTian** [comment]
PR welcome.

**Comment by aojiaotage** [comment]
#44 
Here's the PR 🎂
Plz notice me if anything needs to be improved.
