### ISSUE TITLE
后台调用getUserByCode API报错

### ISSUE THREAD

**Issue by DiscoverForever** [node-webot/wechat-oauth#48]
appId和appSecret均为正确的小程序信息
```javascript
const client = new OAuth('appId','appSecret', null, null,true);
  client.getUserByCode('code', (err, result) => {
    if (err) {
      console.error('code换取access_token失败', err);
    } else {
      console.log(result);
    }
  });
```

 Error: error occurred when trying to decrypt mini-program user data
    at OAuth.decryptMiniProgramUser (/home/leanengine/app/node_modules/wechat-oauth/lib/oauth.js:336:21)
    at /home/leanengine/app/node_modules/wechat-oauth/lib/oauth.js:483:12
    at /home/leanengine/app/node_modules/wechat-oauth/lib/oauth.js:41:7
    at OAuth.saveToken (/home/leanengine/app/node_modules/wechat-oauth/lib/oauth.js:78:5)
    at /home/leanengine/app/node_modules/wechat-oauth/lib/oauth.js:40:10
    at /home/leanengine/app/node_modules/wechat-oauth/lib/util.js:20:5
    at done (/home/leanengine/app/node_modules/urllib/lib/urllib.js:386:5)
    at /home/leanengine/app/node_modules/urllib/lib/urllib.js:605:9
    at decodeContent (/home/leanengine/app/node_modules/urllib/lib/urllib.js:454:14)
    at IncomingMessage.<anonymous> (/home/leanengine/app/node_modules/urllib/lib/urllib.js:570:7)

![1528097461431](https://user-images.githubusercontent.com/16662687/40904096-4c807b22-680c-11e8-8c20-190d8208cf92.jpg)

**Comment by JacksonTian** [comment]
有上下文数据吗

**Comment by DiscoverForever** [comment]
抱歉 appid和appSecret信息比较敏感 不太方便提供，您这块可以用自己小程序的appid和appSecretce测试该API，这应该是一个普遍的bug。如果您无法复现这个bug请通知我关闭这个issue

**Comment by DiscoverForever** [comment]
问题已解决，初始化OAuth时如果是小程序时(第五个参数为true)，调用getUserByCode方法时第一个参数需传Object对象格式为{encryptedData: '', iv: '',lang:'',code:''}
![1528334665428](https://user-images.githubusercontent.com/16662687/41073160-9a472a48-6a34-11e8-96d8-d51e1775b45c.jpg)

```javascript
const client = new OAuth('appId','appSecret', null, null,true);
  client.getUserByCode({
        encryptedData: '',
        iv: '',
        lang:'',
        code:''
    }, (err, result) => {
    if (err) {
      console.error('code换取access_token失败', err);
    } else {
      console.log(result);
    }
  });
```
API文档其实已经写明参数可以为String||Object只是当时看文档并不知道何时传Object，格式如何，查看源码才解决问题，希望作者能更新下文档对开发者友好些。anyway多谢您的开源项目🎉🎉🎉
