### ISSUE TITLE
getUser方法怎么获取微信中文昵称；

### ISSUE THREAD

**Issue by yonghui666** [node-webot/wechat-oauth#55]
请问这个参数怎么传递；能给个文档不；
![image](https://user-images.githubusercontent.com/49012394/103449397-db453d80-4ce2-11eb-9869-278c2a448c4f.png)

**Comment by terry-fei** [comment]
你这是小程序端的接口吧，这个库是服务端的

**Comment by yonghui666** [comment]
> 你这是小程序端的接口吧，这个库是服务端的

我这就是用在了node服务端啊；微信公众号获取用户信息接口；现在获取的信息的英文；想知道怎么获取中午；老哥；

**Comment by terry-fei** [comment]
https://github.com/node-webot/wechat-oauth/blob/master/lib/oauth.js#L289
https://github.com/node-webot/wechat-oauth/blob/master/lib/oauth.js#L377
这里传个对象进去就可以了

**Comment by yonghui666** [comment]
> https://github.com/node-webot/wechat-oauth/blob/master/lib/oauth.js#L289

感谢老哥；之前没仔细看源码；
