### ISSUE TITLE
JSHint 2.0 以上版本，抛出 ES5 option is now set per default 错误提醒

### ISSUE THREAD

**Issue by plusmancn** [node-webot/wechat-oauth#6]
**修正**
 .jshintrc 文件中移除如下特性，因为JSHint2.0默认是 true
```javascript
"es5":true
```

**参考资料**
[stackoverflow  JsHint - Hide This Message: ES5 option is now set per default](http://stackoverflow.com/questions/24212156/jshint-hide-this-message-es5-option-is-now-set-per-default)
[JSHint社区 ES5 option is now set per default ](https://jslinterrors.com/es5-option-is-now-set-per-default)

**Comment by JacksonTian** [comment]
PR welcome
