### ISSUE TITLE
文档中getAccessToken callback中的err参数描述应该详细点

### ISSUE THREAD

**Issue by pigerla** [node-webot/wechat-oauth#7]
api.getAccessToken(code, function (err, result) { 
      ...
    });

中的err，应该强调这是通过code获取Access_token失败时的错误对象；或者在文档中添加代码demo，例如：

    api.getAccessToken(code, function (err, result) { 
      if ( err ) {
         // 获取Access_token失败时的操作。
      } else {
        // 获取成功的操作。
      }
    });

**Comment by JacksonTian** [comment]
这不是用Node的基本常识吗？第一个参数 err如果存在 表示异步调用失败。
