### ISSUE TITLE
getUserByCode能否加上语言选项？

### ISSUE THREAD

**Issue by klausgao** [node-webot/wechat-oauth#9]
像getUser方法一样，options为一个对象，这样。
{
 "code": "code", // 必须
 "lang": "the lang code" // zh_CN 简体，zh_TW 繁体，en 英语
}
这样能返回中文的信息（国家、省市），比较好。

**Comment by JacksonTian** [comment]
发PR吧。

**Comment by JacksonTian** [comment]
欢迎贡献

**Comment by JacksonTian** [comment]
1.2.0 中完成。
